# Generated by Django 4.0.1 on 2022-03-07 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news_description_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
